;/* Version 6ed9e8be6594938a3179b249648f60c0 v:4.1.8.5, c:74a75417bdc4d911001d3ec69d95d505b8521fff, b:11975 n:60-4.1.8.next-build */(function(){(function(){if(!window.ADRUM&&!0!==window["adrum-disable"]){var g=window.ADRUM={};window["adrum-start-time"]=window["adrum-start-time"]||(new Date).getTime();(function(a){(function(a){a.uc=function(){for(var a=[],c=0;c<arguments.length;c++)a[c-0]=arguments[c];for(c=0;c<a.length;c++){var b=a[c];b&&b.H()}}})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){a=a.conf||(a.conf={});a.beaconUrlHttp="http://col.eum-appdynamics.com";a.beaconUrlHttps="https://col.eum-appdynamics.com";a.corsEndpointPath="/eumcollector/beacons/browser/v1";
a.imageEndpointPath="/eumcollector/adrum.gif?";a.appKey=window["adrum-app-key"]||"AD-AAB-AAB-RCH";var d="https:"===document.location.protocol;a.adrumExtUrl=(d?"https://cdn.appdynamics.com":"http://cdn.appdynamics.com")+"/adrum-ext.6ed9e8be6594938a3179b249648f60c0.js";a.agentVer="4.1.8.5";a.sendImageBeacon="false";if(window["adrum-geo-resolver-url"]){var e=window["adrum-geo-resolver-url"],c=e.indexOf("://");-1!=c&&(e=e.substring(c+3));e=(d?"https://":"http://")+e}else e=d?"":
"";a.geoResolverUrl=e;a.useStrictDomainCookies=!0===window["adrum-use-strict-domain-cookies"];a.userConf=window["adrum-config"];a.jd=10})(g||(g={}));(function(a){(function(d){function e(a){return"undefined"!==typeof a&&null!==a}function c(a){return"[object Array]"===Object.prototype.toString.apply(a)}function b(a){return"object"==typeof a&&!c(a)&&null!==a}function h(a,k){for(var d in k){var q=k[d];if(k.hasOwnProperty(d)&&e(q)){var m=a[d];b(q)&&b(m)?h(m,q):a[d]=c(m)&&c(q)?m.concat(q):
q}}}function k(a){return"string"==typeof a?a.replace(/^\s*/,"").replace(/\s*$/,""):a}d.isDefined=e;d.isArray=c;d.isObject=b;d.isFunction=function(a){return"function"==typeof a||!1};d.Ga=function(a){return"number"==typeof a};d.sc=function(a){setTimeout(a,0)};d.addEventListener=function(b,c,k){function h(){try{return k.apply(this,Array.prototype.slice.call(arguments))}catch(d){a.exception(d,"M1",c,b,d)}}a.isDebug&&a.log("M0",c,b);b.addEventListener?b.addEventListener(c,h,!1):b.attachEvent&&b.attachEvent("on"+
c,h)};d.loadScriptAsync=function(b){var c=document.createElement("script");c.async=!0;c.src=b;var k=document.getElementsByTagName("script")[0];k?(k.parentNode.insertBefore(c,k),a.log("M2",b)):a.log("M3",b)};d.Q=h;d.Gc=function(a){var b=[];a&&(d.isObject(a)?b=[a]:d.isArray(a)&&(b=a));return b};d.generateGUID="undefined"!==typeof window.crypto&&"undefined"!==typeof window.crypto.getRandomValues?function(){function a(b){for(b=b.toString(16);4>b.length;)b="0"+b;return b}var b=new Uint16Array(8);window.crypto.getRandomValues(b);
return a(b[0])+a(b[1])+"_"+a(b[2])+"_"+a(b[3])+"_"+a(b[4])+"_"+a(b[5])+a(b[6])+a(b[7])}:function(){return"xxxxxxxx_xxxx_4xxx_yxxx_xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})};d.parseURI=function(a){return(a=String(a).replace(/^\s+|\s+$/g,"").match(/^([^:\/?#]+:)?(\/\/(?:[^:@]*(?::[^:@]*)?@)?(([^:\/?#]*)(?::(\d*))?))?([^?#]*)(\?[^#]*)?(#[\s\S]*)?/))?{href:a[0]||"",protocol:a[1]||"",J:a[2]||"",host:a[3]||"",hostname:a[4]||"",port:a[5]||"",
pathname:a[6]||"",search:a[7]||"",hash:a[8]||""}:null};d.absolutizeURI=function(a,b){function c(a){var b=[];a.replace(/^(\.\.?(\/|$))+/,"").replace(/\/(\.(\/|$))+/g,"/").replace(/\/\.\.$/,"/../").replace(/\/?[^\/]*/g,function(a){"/.."===a?b.pop():b.push(a)});return b.join("").replace(/^\//,"/"===a.charAt(0)?"/":"")}b=d.parseURI(b||"");a=d.parseURI(a||"");return b&&a?(b.protocol||a.protocol)+(b.protocol||b.J?b.J:a.J)+c(b.protocol||b.J||"/"===b.pathname.charAt(0)?b.pathname:b.pathname?(a.J&&!a.pathname?
"/":"")+a.pathname.slice(0,a.pathname.lastIndexOf("/")+1)+b.pathname:a.pathname)+(b.protocol||b.J||b.pathname?b.search:b.search||a.search)+b.hash:null};d.getFullyQualifiedUrl=function(b){try{return d.absolutizeURI(document.location.href,b)}catch(c){return a.exception(c,"M4",b,document.location.href),b}};d.tryExtractingErrorStack=function(a){return a?(a=a.stack)&&"string"===typeof a?a:null:null};d.xf=function(a){var b={},c,h;if(!a)return b;var d=a.split("\n");for(h=0;h<d.length;h++){var e=d[h];c=e.indexOf(":");
a=k(e.substr(0,c)).toLowerCase();c=k(e.substr(c+1));a&&(b[a]=b[a]?b[a]+(", "+c):c)}return b};d.tryPeriodically=function(a,b,c,k){function h(){if(b())c&&c();else{var e=a(++d);0<e?setTimeout(h,e):k&&k()}}var d=0;h()}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){function d(b,c,h,d){b=a.conf.beaconUrlHttps+"/eumcollector/error.gif?version=1&appKey="+h+"&msg="+encodeURIComponent(b.substring(0,500));d&&(b+="&stack=",b+=encodeURIComponent(d.substring(0,1500-b.length)));return b}function e(b,c){2<=
h||((new Image).src=d(b,0,a.conf.appKey,c),h++)}function c(a){return 0<=a.location.search.indexOf("ADRUM_debug=true")||0<=a.cookie.search(/(^|;)\s*ADRUM_debug=true/)}a.iDR=c;a.isDebug=c(document);var b=[];a.log=function(c){for(var h=1;h<arguments.length;h++);a.isDebug&&b.push(Array.prototype.slice.call(arguments).join(" | "))};a.error=function(b){for(var c=1;c<arguments.length;c++);c=Array.prototype.slice.call(arguments).join(" | ");a.log(c);e(c,null)};a.exception=function(){for(var b=[],c=0;c<arguments.length;c++)b[c-
0]=arguments[c];1>arguments.length||(b=Array.prototype.slice.call(arguments),c=a.utils.tryExtractingErrorStack(b[0]),b=b.slice(1).join(" | "),a.log(b),e(b,c))};a.assert=function(b,c){b||a.error("Assert fail: "+c)};a.dumpLog=a.isDebug?function(){for(var a="",c=0;c<b.length;c++)a+=b[c].replace(RegExp("<br/>","g"),"\n\t")+"\n";return a}:function(){};a.cIEBU=d;var h=0;a.log("M5")})(g||(g={}));(function(a){var d=function(){function a(b){this.max=b;this.za=0}a.prototype.Re=function(){this.ha()||this.za++};
a.prototype.ha=function(){return this.za>=this.max};a.prototype.reset=function(){this.za=0};return a}(),e=function(){function c(){this.ca=[];this.Oa=new d(c.xd);this.Ja=new d(c.md)}c.prototype.submit=function(b){this.push(b)&&a.initEXTDone&&this.processQ()};c.prototype.processQ=function(){for(var b=this.le(),c=0;c<b.length;c++){var k=b[c];"function"===typeof a.commands[k[0]]?(a.isDebug&&a.log("M6",k[0],k.slice(1).join(", ")),a.commands[k[0]].apply(a,k.slice(1))):a.error("M7",k[0])}};c.prototype.af=
function(a){return"reportXhr"===a||"reportPageError"===a};c.prototype.push=function(b){var c=b[0],k=this.af(c),d=k?this.Oa:this.Ja;if(d.ha())return a.log("M8",k?"spontaneous":"non spontaneous",c),!1;this.ca.push(b);d.Re();return!0};c.prototype.le=function(){var a=this.ca;this.reset();return a};c.prototype.size=function(){return this.ca.length};c.prototype.reset=function(){this.ca=[];this.Oa.reset();this.Ja.reset()};c.prototype.isSpontaneousQueueDead=function(){return this.Oa.ha()};c.prototype.isNonSpontaneousQueueDead=
function(){return this.Ja.ha()};c.xd=100;c.md=100;return c}();a.Mc=e})(g||(g={}));(function(a){a.q=new a.Mc;a.command=function(d){for(var e=1;e<arguments.length;e++);a.isDebug&&a.log("M9",d,Array.prototype.slice.call(arguments).slice(1).join(", "));a.q.submit(Array.prototype.slice.call(arguments))}})(g||(g={}));(function(a){(function(d){window.ADRUM.aop=d;d.support=function(a){return!a||"apply"in a};d.around=function(e,c,b,h){a.assert(d.support(e),"aop.around called on a function which does not support interception");
e=e||function(){};return function(){a.isDebug&&a.log("M10",h,Array.prototype.slice.call(arguments).join(", "));var k=Array.prototype.slice.call(arguments),d;try{c&&(d=c.apply(this,k))}catch(l){a.exception(l,"M11",h,l)}a.assert(!d||"[object Array]"===Object.prototype.toString.call(d));var p=void 0;try{p=e.apply(this,d||k)}finally{try{b&&b.apply(this,k)}catch(g){a.exception(g,"M12",h,g)}}return p}};d.before=function(a,c){return d.around(a,c)};d.after=function(a,c){return d.around(a,null,c)}})(a.aop||
(a.aop={}))})(g||(g={}));(function(a){(function(d){var e=function(){function c(){}c.prototype.H=function(){a.aop.support(window.onerror)?(window.onerror=a.aop.around(window.onerror,function(b,h,k,d,l){c.Ha||(c.errorsSent>=a.conf.jd?a.log("M13"):(d=a.utils.tryExtractingErrorStack(l),a.command("reportPageError",b,h,k,d),c.errorsSent++,c.Ha=!0))},function(){c.Ha=!1},"onerror"),a.log("M14")):a.log("M15")};c.Ha=!1;c.errorsSent=0;return c}();d.ErrorMonitor=e;d.te=new d.ErrorMonitor})(a.monitor||(a.monitor=
{}))})(g||(g={}));(function(a){var d=function(){function d(){this.pa=[];this.ja(d.va,0)}d.prototype.nf=function(a){this.ja(d.rb,a)};d.prototype.pf=function(a){this.ja(d.vb,a)};d.prototype.of=function(a){this.ja(d.tb,a)};d.prototype.ja=function(a,b){this.pa.push({mf:(new Date).getTime(),lf:b,fc:a});this.he=a};d.prototype.getPhaseName=function(){return this.he};d.prototype.getPhaseID=function(a){for(var b=0;b<d.ub.length;b++)if(d.ub[b]===a)return b;return null};d.prototype.getPhaseCallbackTime=function(a){for(var b=
this.pa,h=0;h<b.length;h++)if(b[h].fc===a)return b[h].mf;return null};d.prototype.findPhaseAtNominalTime=function(c){a.assert(0<=c);for(var b=this.pa,h=b.length-1;0<=h;h--)if(c>=b[h].lf)return b[h].fc;a.error("M16",c,a.utils.ne(b));return d.va};d.va="AFTER_FIRST_BYTE";d.rb="AFTER_DOM_INTERACTIVE";d.vb="AT_ONLOAD";d.tb="AFTER_ONLOAD";d.ub=[d.va,d.rb,d.vb,d.tb];return d}();a.gg=d;a.lifecycle=new d;a.lifecycle=a.lifecycle})(g||(g={}));(function(a){(function(d){var e=function(){function c(){}c.prototype.H=
function(){c.Hf();c.Gf()};c.Gf=function(){a.utils.addEventListener(window,"load",c.ka);a.utils.addEventListener(window,"load",c.sf)};c.sf=function(b){a.lifecycle.pf(b&&b.timeStamp);a.utils.sc(function(){var b=(new Date).getTime();a.lifecycle.of(b);a.command("mark","onload",b);d.ob.k&&(d.perfMonitor.ee(),d.perfMonitor.fe());a.command("reportOnload");a.utils.loadScriptAsync(a.conf.adrumExtUrl)});a.log("M17")};c.Hf=function(){if(document.addEventListener)document.addEventListener("DOMContentLoaded",
c.Y,!1);else{document.attachEvent("onreadystatechange",c.Y);var b=null;try{b=null===window.frameElement?document.documentElement:null}catch(d){}null!=b&&b.doScroll&&function f(){if(!c.isReady){try{b.doScroll("left")}catch(a){setTimeout(f,10);return}c.ka()}}()}a.log("M18")};c.ka=function(b){c.ac||(a.lifecycle.nf(b&&b.timeStamp),a.command("mark","onready",(new Date).getTime()),c.ac=!0)};c.Y=function(a){document.addEventListener?(document.removeEventListener("DOMContentLoaded",c.Y,!1),c.ka(a)):"complete"===
document.readyState&&(document.detachEvent("onreadystatechange",c.Y),c.ka(a))};c.isReady=!1;c.ac=!1;return c}();d.Nc=e;d.ke=new d.Nc})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){var d=function(){function a(){this.B={};this.ya=function(a){return e.ya.call(this,a)}}a.prototype.now=function(){return e.now()};a.prototype.mark=function(a,c){e.mark.apply(this,arguments)};a.prototype.measure=function(a,c,d){e.measure.apply(this,arguments)};a.prototype.getEntryByName=function(a){return e.getEntryByName.call(this,
a)};return a}();a.Dd=d;var e;(function(c){c.now;c.mark;c.measure;c.getEntryByName;c.ya;var b=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance,d=b&&b.timing&&b.timing.navigationStart?b.timing.navigationStart:window["adrum-start-time"];c.now=b&&b.now?function(){return b.now()}:function(){return(new Date).getTime()-d};c.mark=function(a,b){this.B[a]={name:a,entryType:"mark",startTime:b?b:c.now(),duration:0}};c.measure=function(b,f,l){this.B.hasOwnProperty(f)&&
this.B.hasOwnProperty(l)?this.B[b]={name:b,entryType:"measure",startTime:f?this.B[f].startTime:d,duration:(l?this.B[l].startTime:c.now())-(f?this.B[f].startTime:0)}:a.error("M19"+(this.B.hasOwnProperty(f)?l:f)+" does not exist. ")};c.getEntryByName=function(a){return this.B[a]||null};c.ya=function(a){return a-d}})(e||(e={}))})(g||(g={}));(function(a){(function(d){var e=function(){function c(){this.navTiming=this.resTiming=null}c.prototype.H=function(){c.k=window.performance||window.mozPerformance||
window.msPerformance||window.webkitPerformance};c.prototype.ee=function(){var b=c.k;if(b=b&&b.timing)if(b.navigationStart&&b.navigationStart<=b.loadEventEnd){var d={},k;for(k in b){var f=b[k];"number"===typeof f&&(d[k]=f)}this.navTiming=d}else a.log("M21");else a.log("M20")};c.prototype.fe=function(){this.resTiming=this.Kb()};c.prototype.Kb=function(){var b=c.k,d=[];b&&b.getEntriesByType&&(b=b.getEntriesByType("resource"))&&b.length&&0<b.length&&b.unshift&&(d=b);0==d.length&&a.log("M22");return d};
c.k=null;return c}();d.ob=e;d.perfMonitor=new d.ob})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){(function(d){var e=function(){function c(){this.conf=null;this.Pa=!1;this.status={};this.T={};!0===window["adrum-xhr-disable"]?a.log("M23"):window.XMLHttpRequest?(this.conf={exclude:[{urls:[{pattern:a.conf.beaconUrlHttp+a.conf.corsEndpointPath},{pattern:a.conf.beaconUrlHttps+a.conf.corsEndpointPath}]}],include:[]},c.jc(this.conf,a.conf.userConf&&a.conf.userConf.xhr),(this.d=window.XMLHttpRequest.prototype)?
"open"in this.d&&"send"in this.d?(this.Pa=a.aop.support(this.d.open)&&a.aop.support(this.d.send))||a.log("M27"):a.log("M26"):a.log("M25")):a.log("M24")}c.jc=function(b,d){d&&(d.include=a.utils.Gc(d.include),d.exclude=a.utils.Gc(d.exclude),a.utils.Q(b,d));var k=b.exclude;if(k)for(var f=0;f<k.length;f++){var l=k[f].urls;l&&0<l.length&&(k[f].urls=c.zb(l))}if(k=b.include)for(f=0;f<k.length;f++)(l=k[f].urls)&&0<l.length&&(k[f].urls=c.zb(l))};c.zb=function(b){for(var c=[],d=0;d<b.length;d++){var f=b[d].pattern;
if("string"===typeof f)try{c.push(new RegExp(f))}catch(l){a.exception(l,"Parse regex pattern failed.")}else a.error("xhr filter pattern should be a string")}return c};c.Kf=function(a,d,k){var f=k&&k.include;k=k&&k.exclude;return f&&0<f.length&&!c.Wb(d,a,f)||k&&0<k.length&&c.Wb(d,a,k)};c.prototype.me=function(a){var c=this.T[a];delete this.T[a];return c||[]};c.prototype.set=function(a,c){this.status[a]=c};c.prototype.H=function(){if(this.Pa){a.log("M28");a.xhrConstructor=window.XMLHttpRequest;a.xhrOpen=
this.xhrOpen=this.d.open;a.xhrSend=this.xhrSend=this.d.send;var b=this;this.d.open=a.aop.around(this.d.open,function(){var d=1<=arguments.length?String(arguments[0]):"",k=2<=arguments.length?String(arguments[1]):"";!c.Kf(k,d,b.conf)&&(this._adrumXhrData={method:d,url:k,sendTime:null,firstByteTime:null,respAvailTime:null,respProcTime:null,parentPhase:null},a.utils.Q(this._adrumXhrData,b.status),d=this._adrumXhrData.tag)&&(a.log("M29"+d+" event with tag "+d),b.T[d]||(b.T[d]=[]),b.T[d].push(this))},
null,"XHR.open");this.d.send=a.aop.around(this.d.send,function(){var d=this,k=d._adrumXhrData;if(k){var f=(new Date).getTime();a.assert(null===k.sendTime,"M30");k.sendTime=k.sendTime||f;k.parentPhase=a.lifecycle.getPhaseName();c.Ze(k.url)?d.setRequestHeader("ADRUM","isAjax:true"):a.log("M31",document.location.href,k.url);var l=0,e=function(){if(4==d.readyState)a.log("M32"),b.qa(d);else{var k=null;try{k=d.onreadystatechange}catch(f){a.log("M33",f);b.qa(d);return}l++;k?a.aop.support(k)?(d.onreadystatechange=
b.Ab(k,d,"XHR.onReadyStateChange"),a.log("M34",l)):(a.log("M35"),b.qa(d)):l<c.Pd?a.utils.sc(e):(a.log("M36"),b.qa(d))}};e()}},null,"XHR.send");"addEventListener"in this.d&&"removeEventListener"in this.d&&a.aop.support(this.d.addEventListener)&&a.aop.support(this.d.removeEventListener)?(this.d.addEventListener=a.aop.around(this.d.addEventListener,this.ge(),null,"XHR.addEventListener"),this.d.removeEventListener=a.aop.around(this.d.removeEventListener,function(b,d){if(this._adrumXhrData){var c=Array.prototype.slice.call(arguments);
d.__adrumInterceptor?(c[1]=d.__adrumInterceptor,a.log("M37")):a.log("M38");return c}},null,"XHR.removeEventListener")):a.log("M39");a.log("M40")}};c.jf=function(a,d){for(var c=!1,f=0;f<d.length;f++){var l=d[f];if(l&&l.test(a)){c=!0;break}}return c};c.Wb=function(a,d,k){var f=!1;if(d&&k)for(var l=0;l<k.length;l++){var e=k[l];if(!(e.method&&a!==e.method||e.urls&&!c.jf(d,e.urls))){f=!0;break}}return f};c.Ze=function(a){var d=document.createElement("a");d.href=a;a=document.location;return":"===d.protocol&&
""===d.hostname&&""===d.port||d.protocol===a.protocol&&d.hostname===a.hostname&&d.port===a.port};c.Pb=function(b){var d=b._adrumXhrData;if(d){var c=(new Date).getTime();2==b.readyState?d.firstByteTime=d.firstByteTime||c:4==b.readyState&&(a.assert(null===d.respAvailTime,"M41"),d.respAvailTime=d.respAvailTime||c,d.firstByteTime=d.firstByteTime||c)}};c.prototype.Ab=function(b,d,k){return c.$f(b,function(){c.Pb(this)},function(){var b=d._adrumXhrData;if(b&&4==d.readyState){var c=(new Date).getTime();
a.assert(null===b.respProcTime,"M42");b.respProcTime=b.respProcTime||c;a.utils.isDefined(b.tag)||a.command("reportXhr",d,b)}},k)};c.prototype.qa=function(b){if(b._adrumXhrData){var d=(new Date).getTime()+3E4,k=function(){c.Pb(b);var f=b._adrumXhrData;if(f){var l=(new Date).getTime();4==b.readyState?(a.assert(null===f.respProcTime,"M43"),f.respProcTime=f.respProcTime||l,a.log("M44"),a.utils.isDefined(f.tag)||a.command("reportXhr",b,f),a.utils.isDefined(b._adrumXhrData.tag)||delete b._adrumXhrData):
l<d?setTimeout(k,c.Za):(a.utils.isDefined(b._adrumXhrData.tag)||delete b._adrumXhrData,a.log("M45"))}};k()}};c.$f=function(b,d,c,f){var l=b;b&&"object"===typeof b&&"toString"in b&&"[xpconnect wrapped nsIDOMEventListener]"===b.toString()&&"handleEvent"in b&&(l=function(){b.handleEvent.apply(this,Array.prototype.slice.call(arguments))});return a.aop.around(l,d,c,f)};c.prototype.ge=function(){for(var b=0;b<arguments.length;b++);var d=this;return function(b,c){if(("load"===b||"error"===b)&&c&&this._adrumXhrData){var l;
l=c;if(l.__adrumInterceptor)l=l.__adrumInterceptor;else if(a.aop.support(l)){var e=d.Ab(l,this,"XHR.invokeEventListener");l=l.__adrumInterceptor=e}else l=null;if(l)return e=Array.prototype.slice.call(arguments),e[1]=l,a.log("M46"),e;a.log("M47",b,c)}}};c.Pd=5;c.Za=50;return c}();d.ua=e;d.w=new d.ua})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){(function(d){function e(a,b){var d=[],c=/^\s*(ADRUM_BT\w*)=(.*)\s*$/i.exec(a);if(c){var e=c[1],c=c[2].replace(/^"|"$/g,""),c=decodeURIComponent(c).split("|"),
g=c[0].split(":");if("R"===g[0]&&Number(g[1])===b)for(h(e),e=1;e<c.length;e++)d.push(c[e])}return d}function c(a,b){var d=/^\s*(ADRUM_(\d+)_(\d+)_(\d+))=(.*)\s*$/i.exec(a);if(d){var c=d[1],e=d[4],g=d[5];if(Number(d[3])===b)return h(c),{index:Number(e),value:g}}return null}function b(b){var d=/^\s*ADRUM=s=([\d]+)&r=(.*)\s*/.exec(b);if(d){a.log("M50",b);if(3===d.length)return h("ADRUM"),{startTime:Number(d[1]),startPage:d[2]};a.error("M51",b);return null}}function h(b){a.log("M49",b);var d=new Date;
d.setTime(d.getTime()-1E3);document.cookie=b+"=;Expires="+d.toUTCString()}d.startTimeCookie=null;d.cookieMetadataChunks=null;d.Db=function(k,h){a.log("M48");for(var l=h?h.length:0,g=[],q=k.split(";"),m=0;m<q.length;m++){var n=q[m],t=c(n,l);t?g.push(t):(n=b(n),null!=n&&(d.startTimeCookie=n))}Array.prototype.sort.call(g,function(a,b){return a.index-b.index});n=[];for(m=0;m<g.length;m++)n.push(g[m].value);for(m=0;m<q.length;m++)(g=e(q[m],l))&&0<g.length&&(n=n.concat(g));d.cookieMetadataChunks=n};a.correlation.eck=
d.Db})(a.correlation||(a.correlation={}))})(g||(g={}));(function(a){"APP_KEY_NOT_SET"===a.conf.appKey&&"undefined"!==typeof console&&"undefined"!==typeof console.log&&console.log("AppDynamics EUM cloud application key missing. Please specify window['adrum-app-key']");a.correlation.Db(document.cookie,document.referrer);a.command("mark","firstbyte",window["adrum-start-time"]);a.monitor.uc(a.monitor.te,a.monitor.ke,a.monitor.perfMonitor,a.monitor.w)})(g||(g={}));(function(a){a=a.ng||(a.ng={});a=a.b||
(a.b={});a.Zb="locationChangeStart";a.df="locationChangeSuccess";a.pc="routeChangeStart";a.qc="routeChangeSuccess";a.vc="stateChangeStart";a.wc="stateChangeSuccess";a.Bc="viewContentLoaded";a.Pe="includeContentRequested";a.Oe="includeContentLoaded";a.da="digest";a.sg="outstandingRequestsComplete";a.wb="beforeNgXhrRequested";a.sb="afterNgXhrRequested";a.rg="ngXhrLoaded";a.xb="$$completeOutstandingRequest"})(g||(g={}));(function(a){a=a.ng||(a.ng={});a=a.c||(a.c={});a.V="viewChangeStart";a.Ua="viewChangeEnd";
a.W="viewDOMLoaded";a.Wa="xhrRequestsCompleted";a.Yf="viewFragmentsLoaded";a.Cc="viewResourcesLoaded";a.Ec="virtualPageStart";a.Dc="virtualPageEnd"})(g||(g={}));(function(a){(function(a){function e(b,c,k,f,l,e){if(c)try{return c.apply(b,[k,f,l].concat(e))}catch(g){return b.error(k,f,l,e,a.$a.Vc,"an exception occurred in a caller-provided callback function",g)}}function c(b,c){return function(){var k=this.current,f=c[k]||c[a.aa]||k,l=Array.prototype.slice.call(arguments);if(this.ce(b))return this.error(b,
k,f,l,a.$a.Wc,"event "+b+" inappropriate in current state "+this.current);if(!1===e(this,this["onbefore"+b],b,k,f,l))return a.Z.Xa;f===a.aa&&(f=k);if(k===f)return e(this,this["onafter"+b]||this["on"+b],b,k,f,l),a.Z.zd;var g=this;this.transition=function(){g.transition=null;g.current=f;e(g,g["onenter"+f]||g["on"+f],b,k,f,l);e(g,g["onafter"+b]||g["on"+b],b,k,f,l);return a.Z.Hd};if(!1===e(this,this["onleave"+k],b,k,f,l))return this.transition=null,a.Z.Xa;if(this.transition)return this.transition()}}
a.VERSION="2.3.5";a.Z={Hd:1,zd:2,Xa:3,eg:4};a.$a={Wc:100,fg:200,Vc:300};a.aa="*";a.create=function(b,h){function k(b){var c=b.from instanceof Array?b.from:b.from?[b.from]:[a.aa];m[b.name]=m[b.name]||{};for(var k=0;k<c.length;k++)n[c[k]]=n[c[k]]||[],n[c[k]].push(b.name),m[b.name][c[k]]=b.to||c[k]}var f="string"==typeof b.initial?{state:b.initial}:b.initial,l=h||b.target||{},e=b.events||[],g=b.callbacks||{},m={},n={};f&&(f.event=f.event||"startup",k({name:f.event,from:"none",to:f.state}));for(var t=
0;t<e.length;t++)k(e[t]);for(var u in m)m.hasOwnProperty(u)&&(l[u]=c(u,m[u]));for(u in g)g.hasOwnProperty(u)&&(l[u]=g[u]);l.current="none";l.og=function(a){return a instanceof Array?0<=a.indexOf(this.current):this.current===a};l.be=function(b){return!this.transition&&(m[b].hasOwnProperty(this.current)||m[b].hasOwnProperty(a.aa))};l.ce=function(a){return!this.be(a)};l.pa=function(){return n[this.current]};l.error=b.error||function(a,b,c,d,k,h,f){throw f||h;};if(f&&!f.defer)l[f.event]();return l}})(a.pb||
(a.pb={}))})(g||(g={}));(function(a){var d=a.ng||(a.ng={}),d=d.conf||(d.conf={});d.disabled=a.conf.userConf&&a.conf.userConf.spa&&a.conf.userConf.spa.angular&&a.conf.userConf.spa.angular.disable;d.xhr={};d.metrics={includeResTimingInEndUserResponseTiming:!0};a.conf.userConf&&a.conf.userConf.spa&&a.conf.userConf.spa.angular&&a.conf.userConf.spa.angular.vp&&(a.conf.userConf.spa.angular.vp.xhr&&a.monitor.ua.jc(d.xhr,a.conf.userConf.spa.angular.vp.xhr),a.conf.userConf.spa.angular.vp.metrics&&a.utils.Q(d.metrics,
a.conf.userConf.spa.angular.vp.metrics))})(g||(g={}));(function(a){a=a.ng||(a.ng={});a.dc={qg:{start:a.c.Ec,end:a.c.Dc,name:"PLT"},kg:{start:a.c.V,end:a.c.Ua,name:"DDT"},pg:{start:a.c.V,end:a.c.W,name:"DRT"},bg:{start:a.c.Ua,end:a.c.W,name:"DPT"},cg:{start:a.c.V,end:a.c.W,name:"DOM"}}})(g||(g={}));(function(a){(function(d){var e=function(){function c(b){this.Vb=!0;this.identifier={};this.R={};this.resTiming=[];this.Cb=this.N=0;this.k=new a.Dd;b&&(this.identifier=b);this.Me=a.utils.generateGUID()}
c.ue=function(b){var c={};b&&b.g?(c.g={vf:""},a.utils.Q(c.g,{vf:b.g.originalPath,Of:b.g.template,Pf:b.g.templateUrl})):b&&b.state&&(c.state={url:""},a.utils.Q(c.state,{url:b.state.url,name:b.state.name,Of:b.state.template,Pf:b.state.templateUrl}));return c};c.prototype.Wf=function(a){this.identifier=c.ue(a)};c.prototype.hf=function(){this.mark(d.c.V);this.mark(d.c.Ec,this.fa(d.c.V))};c.prototype.gf=function(){var b=this.fa(d.c.W),c=this.fa(d.c.Wa),b=Math.max(b,c);d.conf.metrics.includeResTimingInEndUserResponseTiming&&
(c=this.fa(d.c.Cc),c=Math.max(b,c),a.log("adjust vp end from %s to %s",b,c),b=c);this.mark(d.c.Dc,b)};c.prototype.xa=function(){var a={},c;for(c in d.dc){var k=d.dc[c];if(this.k.getEntryByName(k.start)&&this.k.getEntryByName(k.end)){this.k.measure(k.name,k.start,k.end);var f=this.k.getEntryByName(k.name);a[k.name]=f&&0<=f.duration&&f.duration||null}}a.PLC=1;a.VDC=this.Cb;for(c in a)a[c]=Math.round(a[c]);return a};c.prototype.se=function(b){var c=this.identifier;b=b.identifier;var d=!1;return d=!a.utils.isDefined(c)&&
!a.utils.isDefined(b)||c===b?!0:a.utils.isDefined(c)&&a.utils.isDefined(b)?c.state||b.state?a.utils.isDefined(c.state)&&a.utils.isDefined(b.state)?c.state.name===b.state.name&&c.state.template===b.state.template&&c.state.templateUrl===b.state.templateUrl&&c.state.url===b.state.url:!1:c.g&&b.g?c.g.originalPath===b.g.originalPath&&c.g.template===b.g.template&&c.g.templateUrl===b.g.templateUrl:c.url===b.url:!1};c.prototype.mark=function(a,c){this.k.mark(a,c)};c.prototype.da=function(){this.Cb++};c.prototype.Qe=
function(){this.N++;a.log("increasing xhr count "+this.N+" pending xhr requests")};c.prototype.ie=function(){this.N--;a.log("decreasing xhr count "+this.N+" pending xhr requests")};c.prototype.Ne=function(){var b=this.k.getEntryByName(d.c.Wa);a.log("xhrCount "+this.N+" xhrReuqestCompleted "+b);return 0<this.N};c.prototype.fa=function(a){return(a=this.k.getEntryByName(a))&&a.startTime};c.prototype.$d=function(){var a={oa:0},d=document.querySelectorAll("ng-view, [ng-view], .ng-view, [ui-view]");if(d&&
0<d.length)for(var k in c.oc)for(var f=0;f<d.length;f++){var l=angular.element(d[f]).find(k);if(0<l.length)for(var e=0;e<l.length;e++){var g=l[e][c.oc[k].Sa];(g=g?decodeURIComponent(g):null)&&!a[g]&&(a[g]=k,a.oa++)}}this.R=a};c.prototype.Zd=function(a){return!!this.R[decodeURIComponent(a.name)]};c.prototype.ae=function(){var b=[],c=this;0<this.R.oa&&(b=a.monitor.perfMonitor.Kb().filter(function(a){return c.Zd(a)}));this.resTiming=b};c.prototype.Ud=function(){if(0<this.R.oa&&(this.ae(),this.resTiming&&
this.resTiming.length>=this.R.oa)){for(var a=[],c=0;c<this.resTiming.length;c++)a.push(this.resTiming[c].responseEnd);a=Math.max.apply(Math,a);this.k.mark(d.c.Cc,a)}};c.prototype.buildMetrics=function(){d.conf.metrics.includeResTimingInEndUserResponseTiming&&this.Ud();this.gf();return this.xa()};c.prototype.getGUID=function(){return this.Me};c.prototype.getResTiming=function(){return this.resTiming};c.prototype.getPageUrl=function(){return this.identifier.url};c.oc={img:{Sa:"src"},script:{Sa:"src"},
link:{Sa:"href"}};return c}();d.VirtualPage=e})(a.ng||(a.ng={}))})(g||(g={}));(function(a){(function(d){var e=function(){function c(){this.e=new d.VirtualPage}c.prototype.Cf=function(){var b=this;d.conf.metrics.includeResTimingInEndUserResponseTiming?(a.log("M52"),setTimeout(function(){b.La()},c.Jd)):setTimeout(function(){b.La()},c.Kd)};c.prototype.La=function(){a.log("M53");for(var b=a.monitor.w.me(this.e.getGUID()),c=0;c<b.length;c++)a.command("reportXhr",b[c],b[c]._adrumXhrData);a.command("reportEvent",
"VPLoad",this.e)};c.If=function(b){var c=b.getGUID(),d=b.getPageUrl();a.log("M54",c,d);a.monitor.w.set("parentGUID",c);a.monitor.w.set("parentType",3);a.monitor.w.set("parentUrl",d);a.monitor.w.set("tag",b.getGUID())};c.de=function(){a.log("M55");a.monitor.w.set("parentGUID",null);a.monitor.w.set("parentType",null);a.monitor.w.set("parentUrl",null);a.monitor.w.set("tag",null)};c.prototype.Ff=function(a){this.e=a};c.prototype.mark=function(a){this.e.mark(a)};c.Jd=5E3;c.Kd=2*a.monitor.ua.Za;return c}();
d.VirtualPageStateMachine=e;a.pb.create({events:[{name:"start",from:"none",to:"ChangeView"},{name:"viewLoaded",from:"ChangeView",to:"XhrPending"},{name:"xhrCompleted",from:"XhrPending",to:"End"},{name:"abort",from:"*",to:"none"},{name:"init",from:"*",to:"none"},{name:"locChange",from:"*",to:"*"},{name:"beforeXhrReq",from:"*",to:"*"},{name:"afterXhrReq",from:"*",to:"*"}],error:function(c){a.log("M56"+c)},callbacks:{onChangeView:function(){this.e.hf()},onviewLoaded:function(){this.mark(d.c.W)},onXhrPending:function(){this.e.Vb&&
this.xhrCompleted()},onleaveXhrPending:function(a,b,e){if("abort"===a)return this.La(),!0;if("xhrCompleted"===a&&"End"===e){if(this.e.Ne())return!1;this.mark(d.c.Wa);return!0}},onEnd:function(){this.e.$d();this.Cf()},oninit:function(a,b,d,k){this.Ff(k)},onlocChange:function(a,b,d,k){this.e.identifier.url=k},onbeforeXhrReq:function(c,b,g,k){var f=this.e;f.Vb=!1;a.log("M57",k&&k[1]||"",this.e.getGUID());f.Qe();e.If(f);k[3]&&(k[3]=a.aop.before(k[3],function(b,c,k){a.log("M58");f.ie();k&&(b=a.utils.xf(k)["content-type"])&&
0<=b.indexOf("text/html")&&f.mark(d.c.Yf)}));return k},onafterXhrReq:function(){e.de()}}},e.prototype)})(a.ng||(a.ng={}))})(g||(g={}));(function(a){(function(d){var e=function(){function c(){this.n=new d.VirtualPageStateMachine}c.prototype.j=function(b,c){a.log("M59",b);switch(b){case d.b.pc:case d.b.vc:this.n.start();var k=new d.VirtualPage(c.next);this.n.e.se(k)?this.n.e.Wf(c.next):this.Nf(k);break;case d.b.qc:case d.b.wc:this.n.e.mark(d.c.Ua);break;case d.b.Bc:this.n.viewLoaded();break;case d.b.wb:this.n.beforeXhrReq(c);
break;case d.b.sb:this.n.afterXhrReq();break;case d.b.xb:this.n.xhrCompleted();break;case d.b.Zb:this.n.locChange(c.next.url);break;case d.b.da:this.n.e.da()}};c.prototype.Nf=function(a){this.n.abort();this.n.init(a);this.n.start()};return c}();d.Nd=e})(a.ng||(a.ng={}))})(g||(g={}));(function(a){(function(d){var e=function(){function c(){this.l=new d.Nd}c.prototype.H=function(){var b=this;a.utils.addEventListener(document,"DOMContentLoaded",function(){a.log("M60");b.init()})};c.prototype.init=function(){if("undefined"!=
typeof angular){a.log("M61");var b=this,c=angular.module("ng");c.config(["$provide",function(a){b.Ve(a);b.Ue(a)}]);c.run(["$browser",function(a){b.Te(a)}]);a.log("M62")}};c.prototype.Ue=function(b){var c=a.aop,k=this;b.decorator("$httpBackend",["$delegate",function(a){return a=c.around(a,function(){var a=Array.prototype.slice.call(arguments);k.l.j(d.b.wb,a);return a},function(){k.l.j(d.b.sb)})}])};c.prototype.Ve=function(b){var c=a.aop,k=this;b.decorator("$rootScope",["$delegate",function(a){a.$digest=
c.after(a.$digest,function(){k.l.j(d.b.da)});a.$on("$locationChangeStart",function(a,b){var c={url:b},e=a&&a.P&&a.P.$state&&a.P.$state.current;e&&(c.state=e);k.l.j(d.b.Zb,{next:c})});a.$on("$locationChangeSuccess",function(){k.l.j(d.b.df)});a.$on("$routeChangeStart",function(a,b){var c={url:location.href},e=b&&b.$$route;e&&(c.g=e);k.l.j(d.b.pc,{next:c})});a.$on("$routeChangeSuccess",function(){k.l.j(d.b.qc)});a.$on("$stateChangeStart",function(a,b){k.l.j(d.b.vc,{next:{state:b}})});a.$on("$stateChangeSuccess",
function(){k.l.j(d.b.wc)});a.$on("$viewContentLoaded",function(a){var b={url:location.href};if(a=a&&a.P&&a.P.$state&&a.P.$state.current)b.state=a;k.l.j(d.b.Bc,{next:b})});a.$on("$includeContentRequested",function(){k.l.j(d.b.Pe)});a.$on("$includeContentLoaded",function(){k.l.j(d.b.Oe)});return a}])};c.prototype.Te=function(b){var c=this;b.$$completeOutstandingRequest=a.aop.before(b.$$completeOutstandingRequest,function(){c.l.j(d.b.xb)})};return c}();d.ag=e;d.ngMonitor=new e})(a.ng||(a.ng={}))})(g||
(g={}));(function(a){var d=a.ng||(a.ng={});d.conf.disabled||a.monitor.uc(d.ngMonitor)})(g||(g={}))}})();})();

